stages:
- build


build_images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    #DOCKER_HOST: tcp://docker:2375
    IMAGE_NAME_API: "image-uploader-api"
    IMAGE_NAME_CLIENT: "image-uploader-client"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:

  # Build images with commit SHA
    - docker build --file ./apps/client/Dockerfile_build --target runner -t $CI_REGISTRY_IMAGE/$IMAGE_NAME_CLIENT:$CI_COMMIT_SHORT_SHA .
    - docker build --file ./apps/api/Dockerfile_build --target runner -t $CI_REGISTRY_IMAGE/$IMAGE_NAME_API:$CI_COMMIT_SHORT_SHA .

  # Retag images latest with digest from previous images
    - IMAGE_ID_CLIENT=$(docker images | grep $CI_REGISTRY/$CI_PROJECT_PATH\/$IMAGE_NAME_CLIENT | awk '{print $3}')
    - IMAGE_ID_API=$(docker images | grep $CI_REGISTRY/$CI_PROJECT_PATH\/$IMAGE_NAME_API | awk '{print $3}')

    - docker tag $IMAGE_ID_CLIENT $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME_CLIENT:latest
    - docker tag $IMAGE_ID_API $CI_REGISTRY/$CI_PROJECT_PATH/$IMAGE_NAME_API:latest

  # Push images commit sha and latest
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME_API:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME_API:latest

    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME_CLIENT:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME_CLIENT:latest
  only:
    - main
    - develop
  tags:
    - build
    - docker
    - vm
