version: "3.9"

services:
  client:
    container_name: image-uploader-client
    build:
        context: .
        dockerfile: ./apps/client/Dockerfile
        target: runner
    environment:
        - PORT=3000
    expose:
      - "3000"
    env_file:
          - prod.client.env
    networks:
      - app-network
  api:
    container_name: image-uploader-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: runner
    expose:
      - "3000"
    env_file:
      - prod.api.env
    networks:
      - app-network


networks:
    app-network:
      name: app-network