FROM node:alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

# pnpm cannot support turbo prune yet. so need manual create isolated folder https://github.com/vercel/turborepo/issues/534
# RUN pnpm global add turbo
# COPY . .
# RUN turbo prune --scope=web --docker

# Need to change to correct app folder name for each flow [ deps, builder, runner ]
# set your APP_NAME
ENV APP_NAME=client

# Create apps folder
RUN mkdir -p apps

# Copy related packages and apps, warning: this solution can't copy package that only needed for the build.
COPY ./packages /app/packages
COPY ./apps/$APP_NAME /app/apps/$APP_NAME

# Copy clean root files to root folder
COPY ./turbo.json /app/turbo.json
COPY ./.gitignore /app/.gitignore
COPY ./.npmrc /app/.npmrc
# Add lockfile and package.json's of isolated subworkspace
COPY ./package.json /app/package.json
COPY ./pnpm-lock.yaml /app/pnpm-lock.yaml
COPY ./pnpm-workspace.yaml /app/pnpm-workspace.yaml


# 2. Rebuild the source code only when needed
FROM node:alpine AS builder
WORKDIR /app

SHELL ["/bin/sh", "-c"]

# set your APP_NAME
ENV APP_NAME=client


COPY --from=deps /app/ .

# Install Pnpm
ENV PNPM_HOME="/usr/local/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"

RUN apk update
RUN apk add --no-cache libc6-compat
RUN npm install --global pnpm \
    && SHELL=bash pnpm setup \
    && source /root/.bashrc \
RUN pnpm turbo run build --filter=$APP_NAME
RUN pnpm --filter $APP_NAME --prod deploy pruned

FROM nginx:1.23.3-alpine as runner


WORKDIR /app

# set your APP_NAME
ENV APP_NAME=client

COPY --from=builder /usr/src/app/dist/ /var/www/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'